DROP DATABASE IF EXISTS "Library";
GO

CREATE DATABASE "Library";
GO

USE "Library";
GO

-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-11-13 19:13:56 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE books (
    book_id             VARCHAR(20) NOT NULL,
    title               VARCHAR(50) NOT NULL,
    author_last_name    VARCHAR(25),
    author_firts_name   VARCHAR(25) NOT NULL,
    rating              NUMERIC(2)
)
go

ALTER TABLE Books ADD constraint books_pk PRIMARY KEY CLUSTERED (book_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 
go

CREATE TABLE patrons (
    patron_id       NUMERIC(7) NOT NULL,
    last_name       VARCHAR(25) NOT NULL,
    first_name      VARCHAR(25),
    street_adress   VARCHAR(40),
    city            VARCHAR(25),
    state           VARCHAR(2),
    zip             VARCHAR(10),
    location        VARCHAR(50)
)
go

ALTER TABLE Patrons ADD constraint patrons_pk PRIMARY KEY CLUSTERED (patron_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 
	 go

CREATE TABLE transactions (
    transaction_id      NUMERIC(7) NOT NULL,
    transaction_date    datetime NOT NULL,
    transaction_type    NUMERIC(7) NOT NULL,
    books_book_id       VARCHAR(20) NOT NULL,
    patrons_patron_id   NUMERIC(7) NOT NULL,
    book_id             varchar NOT NULL
)
go

ALTER TABLE Transactions ADD constraint transactions_pk PRIMARY KEY CLUSTERED (transaction_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 
 go

ALTER TABLE Transactions
    ADD CONSTRAINT transactions_books_fk FOREIGN KEY ( books_book_id )
        REFERENCES books ( book_id )
ON DELETE NO ACTION 
    ON UPDATE no action 
go

ALTER TABLE Transactions
    ADD CONSTRAINT transactions_patrons_fk FOREIGN KEY ( patrons_patron_id )
        REFERENCES patrons ( patron_id )
ON DELETE NO ACTION 
    ON UPDATE no action 
go



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
